"""empty message

Revision ID: 09c5f6d52141
Revises: 
Create Date: 2020-07-27 22:44:35.251423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c5f6d52141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('data_cadastro', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'data_cadastro')
    # ### end Alembic commands ###
